# -*- coding: utf-8 -*-
"""FloodPred.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1htHtKTk2oSteym4kShdqLQUtrexGU7D4
"""

import numpy as np
import pandas as pd
import pickle

data = pd.read_csv('kerala.csv')
print(data)

data['FLOODS'].replace(['YES','NO'],[1,0],inplace=True)
data.head()

x=data.iloc[:,1:14]
x.head()

y=data.iloc[:,-1]
y

from sklearn import preprocessing
minmax = preprocessing.MinMaxScaler(feature_range=(0,1))
minmax.fit(x).transform(x)

from sklearn import model_selection,neighbors
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
x_train.head()

y_train=y_train.astype('int')
y_train

y_test=y_test.astype('int')
y_test

x_train_std= minmax.fit_transform(x_train)
x_test_std= minmax.fit_transform(x_test)

from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

pickle.dump(lr, open('model.pkl', 'wb'))

model = pickle.load(open('model.pkl','rb'))